### ISSUE TITLE
Installation order

### ISSUE THREAD

**Issue by albertusQuelle** [CoogyEoin/SaorTech-cloud-services#1]
Hey, 
first of all - thanks - your video as well as the explanation in README looks promising. 

I have a fresh VPS installation of Ubuntu 20.04. 

Can you please tell me in which order i shall install your scripts when i want to have a mail server, next cloud and a website running on my VPS?
I have an own domain pointing to my VPS. 
Or can the scripts simply be combined to an all-in-one-Solution?

Thank you 
cheers

**Comment by CoogyEoin** [comment]
Hey m'lord,

Yeah they don't need to be in any order although a handler script may be a good addition in the future. There will be some installing dependencies overlapping (apache, postgress etc..) but that shouldn't make the scripts fail. If there are any problems with the script please submit an issue and I'll try fix them.

Good luck with your VPS setup,
Eoin.
