### ISSUE TITLE
Open Dovecot and certbot feedback

### ISSUE THREAD

**Issue by albertusQuelle** [CoogyEoin/SaorTech-cloud-services#2]
Hi, i have installed wit the following command

`sudo ./install_mail_server_with_ssl.sh -e halloichbinda@gmail.com -u user1 -p thesecretpass -d domain.de -f mail.domain.de`

How can i now open dovecot? 
When i open https://domain.de i just see the apache startpage. 

Further: i needed to run certbot after the installation to get it run. 
So after the intallation above i could not open https://domain.de
After running
`sudo certbot --apache` it worked generally.

How can i now enter the dovecot webinterface to manage my E-Mail server?
(Ubuntu 20.04)

Thanks

**Comment by CoogyEoin** [comment]
There is no web interface. All the script does is install and configure the services. You can check if the service is running using `sudo systemctl status dovecot`. If you want to set up a web interface of some sort you'll need to add it to the apache files under `/var/www/`.
I personally use mutt as an email client though there's no need to have a web interface.

**Comment by albertusQuelle** [comment]
Cool Thx i will do :)
